### ISSUE TITLE
Missing Installation guide 

### ISSUE THREAD

**Issue by ArnCarveris** [CookiePLMonster/SilentPatchFarCry#1]
Hi, first of all, I need thank you.

But how to install it? what asi file stands for?

**Comment by CookiePLMonster** [comment]
ReadMe file is included in the archive for a reason - it contains installation instructions, for example.

**Comment by ArnCarveris** [comment]
@CookiePLMonster what archive?

**Comment by CookiePLMonster** [comment]
Have you not downloaded one from Releases page?

**Comment by ArnCarveris** [comment]
Oh my bad I was looking [there](https://github.com/ArnCarveris/SilentPatchFarCry/releases/tag/BUILD-1).
