### ISSUE TITLE
Missing mods support

### ISSUE THREAD

**Issue by ArnCarveris** [CookiePLMonster/SilentPatchFarCry#2]
Works fine in vanilla mode, but doesn't in Mod mode, putting files to directory `FarCry/Mods/<mod-name>/Bin32/`  doesn't solve problem.

**Comment by CookiePLMonster** [comment]
What is even Mod mode? Does it allow overriding executables? Seems like the only way to get it to break in this mode.

**Comment by ArnCarveris** [comment]
It just loads `FarCry/Mods/<mod-name>/Bin32/CryGame.dll` if exists.

**Comment by ArnCarveris** [comment]
Be sure that you have enabled `FullDetailTerrain` in `RenderParams`  for each water shader (`Shaders\HWScripts\Techniques\terrainWater.csl`) 

@CookiePLMonster Would be great if mention this in readme
